### ISSUE TITLE
Feedback Request: Python 5-8

### ISSUE THREAD

**Issue by sasudi90** [TechGrounds-Cloud8/cloud8-sasudi90#46]
**Feedback Request [Python 5-8]**
Permalink to file: 

5.1 [PRG 5.1](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-05/conditions1.py)
5.2 [PRG 5.2](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-05/conditions2.py)
6.1 [PRG 6.1](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-06/rndm.py)
6.2 [PRG 6.2](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-06/myFunction.py)
6.3 [PRG 6.3](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-06/avg.py)
7.1 [PRG 7.1](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-07/listOfStrings.py)
7.2 [PRG 7.2](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-07/listOfInts.py)
8.1 [PRG 8.1](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-08/dictionary.py)
8.2 [PRG 8.2](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/eda618b1025cc6a07859ce3f9e3bfd212a982913/07_Python/PRG-08/inputDictionary.py)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
**PRG-05-2:** Nice one! I like how you structured your while loop :) Currently, your Try/Except block will catch ANY error (not just the ones where the input is the wrong data type), so this is considered dangerous. Always try to be as specific as possible and specifiy for which error the exception applies. 

**PRG-07 ints:** What is the code on row 13 for? 

**PRG-08 csv:** IMO V1 was more clean and futureproof when you had the inputs linked to variables and inserted those in the dictionary, but this also works, so no need to change it :)

**Comment by Killian97** [comment]
what ben said about the error in 5-02

nice work in all. 

ps: try not to camelcase!
